Change geo_columns to dict
jataware/elwood pull request #18
Opened 2023-07-12 20:41 UTC by adamgilg

This changes the geo_columns args from lists to dicts in the various transformations.

2023-07-14 16:14 UTC, brandomr commented
This looks good to me. Definitely reminds me we should add some tests for this. @adamgilg if you could send me some example payloads for the various transformations that come from the front end to elwood I could probably crank out tests pretty quickly.

2023-07-14 16:15 UTC, brandomr commented
My inclination is to merge this and @ccjoel to deploy it since it's causing a pretty heinous bug when people clip datasets and I feel like they'll continue registering/clipping even though we have this bug and have provided notice about it. @ccjoel thoughts?

2023-07-17 13:52 UTC, ccjoel commented
> deploy it since it's causing a pretty heinous bug when people clip datasets and I feel like they'll continue registering/clipping even though we have this bug and have provided notice about it.

Yeah, let me coordinate with Adam today to also merge in the corresponding Dojo PR and we can redeploy the stack.

2023-07-17 14:57 UTC, ccjoel requested changes
I took a deeper look on the branch. docstring for the caller of clip_geo (in `elwood/elwood.py`), as an example, still explains that it expects a list instead of a dict. Elwood's top-level [README](https://github.com/jataware/elwood/blob/geo-columns-dict/README.md#geospatial-clipping) also includes mentions of ["lat", "lon"] and should be deplaced with dict examples.

I haven't checked the docs for the rest of the transformations, but we should probably update the docstrings/readme for the rest of the changes to dict as well.

2023-07-17 18:54 UTC, ccjoel commented
I'm updating the README now

2023-07-17 19:05 UTC, ccjoel commented on tests/transformations_test.py
> +        assert 3 == 3
TODO, I don't have a dataset that allows regridding.

2023-07-18 15:45 UTC, Sorrento110 approved these changes
Looks like good changes to me overall. We can go ahead and merge this and I can publish the new version to pypi.

2023-07-18 15:45 UTC, Sorrento110 commented on elwood/elwood.py
> +regrid_dataframe_geo = regrid_dataframe
If we are doing this on one of the entry points we will probably want to do this on all of the entry-points, but I think this is less human-readable as a library entry-point than what we had previously.

2023-07-18 16:28 UTC, merged